ENGINE:
  EVAL_ONLY: true
  MAX_EPOCH: 1
  ATTACK_ALGORITHM: attack_eval
DATA:
  DATASET:
    TEST_NAME: Market1501
    # TEST_NAME: DukeMTMCreID
    # TEST_NAME: MSMT17
  DATALOADER:
    BATCH_SIZE_TEST: 128
  # # fot transreid
  # TRANSFORM:
  #   NORM:
  #     PIXEL_MEAN: [0.5, 0.5, 0.5]
  #     PIXEL_STD: [0.5, 0.5, 0.5]
MODULE:
  TARGET_MODEL:
    NAME: resnet50_bot
    WEIGHT: model_weights/reid_models/ReidStrongBaseline/resnet50/market1501_resnet50_bot_map=0.86.pth